### ISSUE TITLE
Unexpected "object" in source map

### ISSUE THREAD

**Issue by acomagu** [ryoppippi/unplugin-typia#47] opened 2024-06-07 01:53 UTC
When cache is enabled, esbuild throws an error saying that the sourcemap is invalid.

![image](https://github.com/ryoppippi/unplugin-typia/assets/1362750/04a2c8d9-2cc9-48af-aaa7-b8607be93564)

After investigation, I found that this is because esbuild(or unplugin?) can't recognize JSON-stringified SourceMap.

The below patch fixes my issue:

```diff
diff --git a/packages/unplugin-typia/src/core/index.ts b/packages/unplugin-typia/src/core/index.ts
index c4afaa2..9c23772 100644
--- a/packages/unplugin-typia/src/core/index.ts
+++ b/packages/unplugin-typia/src/core/index.ts
@@ -5,6 +5,7 @@ import {
 } from 'unplugin';
 import { createFilter as rollupCreateFilter } from '@rollup/pluginutils';
 import { consola } from 'consola';
+import { SourceMap } from 'magic-string';
 
 import { type Options, resolveOptions } from './options.js';
 import { transformTypia } from './typia.js';
@@ -66,7 +67,10 @@ const unpluginFactory: UnpluginFactory<
 
                        /** return cache if exists */
                        if (cache != null) {
-                               return cache;
+                               return {
+                                       ...cache,
+                                       map: SourceMap(cache.map),
+                               };
                        }
 
                        /** transform if cache not exists */
```

**Comment by ryoppippi** [comment] 2024-06-07 08:07
Hi!
Thank you for your investigation.

I cannot reproduce this issue in my environment(on mac 14, bun), but your fix needs to be merged.

If you are willing to do, I'd like you to create a small patch as PR and send it to me.

> The below patch fixes my issue:
Your pach looks very good, could you change it as follows?
- fix to create `SourceMap` objcet in `getCache` function is `./src/core/cache.ts`, instead of `src/core/index.ts`.
- or stop caching sourcemap (maybe generating sourcemap doesn't cost a lot)

**Closed** 2024-06-07 14:25 UTC
Labels: bug, cache
