### ISSUE TITLE
fails on bun + windows

### ISSUE THREAD

**Issue by stephen-dahl** [ryoppippi/unplugin-typia#237] opened 2024-07-23 01:40 UTC
I am getting an error when running typia with bun.

```sh
 bun run src/server/config.ts

 ╭───────────────────────────────────╮
 │                                   │
 │  [unplugin-typia] Cache disabled  │
 │                                   │
 ╰───────────────────────────────────╯

193 |     [Symbol.dispose]: ()=>transformationResult.dispose()
194 |   };
195 | }
196 | /** Warn diagnostics */ function warnDiagnostic(diagnostics, transformed, unpluginContext) {
197 |   for (const diagnostic of diagnostics){
198 |     unpluginContext.warn(transformed.map((e)=>e.fileName).join(','));
          ^
TypeError: undefined is not an object (evaluating 'unpluginContext.warn')
      at warnDiagnostic (D:\dev\email\node_modules\@ryoppippi\unplugin-typia\src\core\typia.js:198:5)
      at D:\dev\email\node_modules\@ryoppippi\unplugin-typia\src\core\typia.js:91:5
```

bun v1.1.20
typia v6.5.4
unplugin-typia 0.6.10

src/server/config.ts
```ts
import {assert, tags} from "typia";

export interface ENV {
    NODE_ENV: 'production' | 'development'
    HTTP_PORT: string
    SMTP_PORT: string
}

export const {NODE_ENV, HTTP_PORT, SMTP_PORT} = process.env
console.log({NODE_ENV, HTTP_PORT, SMTP_PORT})
```

removing the typia import clears the error

bunfig.toml
```toml
preload = ["./preload.ts"]

[test]
preload = ["./preload.ts"]
```

preload.ts
```ts
import { plugin } from "bun";
import UnpluginTypia from "@ryoppippi/unplugin-typia/bun";

plugin(UnpluginTypia());
```

tsconfig.json
```json
{
  "compilerOptions": {
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": [
      "ES2020",
      "DOM",
      "DOM.Iterable"
    ],
    "module": "ESNext",
    "skipLibCheck": true,
    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "plugins": [
      {
        "transform": "typia/lib/transform"
      }
    ],
    "strictNullChecks": true
  },
  "include": [
    "src"
  ]
}
```

**Comment by ryoppippi** [comment] 2024-07-23 07:12
Please provide reproduction repository

**Comment by ryoppippi** [comment] 2024-07-23 09:28
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Comment by stephen-dahl** [comment] 2024-07-23 20:24
https://github.com/stephen-dahl/bun-typia-error

**Comment by ryoppippi** [comment] 2024-07-24 07:40
@stephen-dahl hi the link is 404

**Comment by stephen-dahl** [comment] 2024-07-24 14:48
oops, was a private repo, fixed now

**Comment by ryoppippi** [comment] 2024-07-24 14:54
looks like it works in my env

**Comment by ryoppippi** [comment] 2024-07-24 15:02
You had to mention that it fails on Windows first...

https://github.com/ryoppippi/bun-typia-error/actions/runs/10079084328

I don't use windows, so idk how to fix it

**Comment by ryoppippi** [comment] 2024-07-24 15:03
Also, please attach GHA first.
It is hard to reproduce...

**Comment by ryoppippi** [comment] 2024-07-24 15:33
https://github.com/ryoppippi/bun-typia-error/actions/runs/10079631063/job/27867411760

fixed.
Try update `unplugin-typia` and if it works fine close this issue @stephen-dahl

**Comment by ryoppippi** [comment] 2024-07-26 22:27
@stephen-dahl any updates?

**Comment by stephen-dahl** [comment] 2024-07-26 23:33
That fixed problem in that repo. Now that is fixed I was able to reproduce the original issue. It looks like it happens when I break up the tsconfig into multiple files using references (like vite does)

Repo updated

my main project is a express server + vite frontend running in the same process.

**Comment by ryoppippi** [comment] 2024-07-27 21:26
This should be another issue 
if you need more support , create a new issue

**Closed by ryoppippi** 2024-07-27 21:26 UTC
Labels: bug, needs repro, bun, windows

**Comment by ryoppippi** [comment] 2024-07-27 21:33
It may be a good idea to greet people you are talking to first :)

**Comment by ryoppippi** [comment] 2024-07-27 21:34
It may be a good idea to greet people you are talking to first :)
@stephen-dahl
