### ISSUE TITLE
Vite plugin doesn't work with Deno

### ISSUE THREAD

**Issue by rlidwka** [ryoppippi/unplugin-typia#285] opened 2024-08-16 12:25 UTC
### unplugin-typia version

0.6.18

### Describe the bug

I'm trying to add unplugin-typia to an existing project.

Simplified config file is this:

```js
import { defineConfig } from "npm:vite";
import react from "npm:@vitejs/plugin-react";
import UnpluginTypia from "jsr:@ryoppippi/unplugin-typia/vite";

export default defineConfig({
  plugins: [
    UnpluginTypia({}),
    react(),
  ],
});
```

Using `deno run -A --node-modules-dir npm:vite build` to run it. Unfortunately, package crashes on import.

### Reproduction

```
$ deno eval 'import UnpluginTypia from "jsr:@ryoppippi/unplugin-typia/vite";'
error: Uncaught (in promise) Error: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received https://jsr.io/@ryoppippi/unplugin-typia/0.6.18/src/core/cache.ts
    at createRequire (node:module:819:13)
    at https://jsr.io/@ryoppippi/unplugin-typia/0.6.18/src/core/cache.ts:11:35
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/ryoppippi/unplugin-typia/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug.
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ryoppippi** [comment] 2024-08-16 14:45
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Comment by rlidwka** [comment] 2024-08-16 15:27
`deno eval 'import UnpluginTypia from "jsr:@ryoppippi/unplugin-typia/vite";'`

that *is* minimal reproduction, please run it to check for yourself

**Comment by rlidwka** [comment] 2024-08-16 16:00
`createRequire(import.meta.url)` does not work when deno pulls package from jsr registry, because `import.meta.url` is gonna be actual url (https://jsr.io/@ryoppippi/unplugin-typia/0.6.18/src/core/cache.ts)

I'm not sure what the intended use for this call is, perhaps bug report against deno should be opened.

**Comment by rlidwka** [comment] 2024-08-16 16:09
https://github.com/denoland/deno/issues/25071

**Comment by ryoppippi** [comment] 2024-08-16 23:03
Ok, @rlidwka 
I think this cache feature only works for node/bun environment because this cache got stored in `node_modules`.
Also, cache is disable in default.
So, maybe we should move get version extraction feature into cache getting function?

I'll work on it tomorrow moning.
If you have any idea to solve this, feel free to send me a patch!!

Cheers and good night!

**Comment by ryoppippi** [comment] 2024-08-16 23:07
Actually, typia does not suport deno because deno doesn't accept build-plugins.
But if this change enables typia to use it in deno, that would be great.

**Comment by ryoppippi** [comment] 2024-08-17 21:32
@rlidwka 
I'll close this issue because,
- you are not creating minimal reproduction repository ( see this issue as a good example https://github.com/ryoppippi/unplugin-typia/issues/283)
- Typia does not support deno

If you want to contribute it, feel free to send us a patch.

**Closed by ryoppippi** 2024-08-17 21:32 UTC

**Comment by ryoppippi** [comment] 2024-08-18 19:45
- we need to support cjs because of webpack, we can't use top-level await 
- We cannot use JSON import because some node env doesn't support it

We tried those two methods above, but some users reported issues related to these implementations. 


so I use the `require` statement. 

If you have some idea for this issue, send us a patch  
@rlidwka
